#pragma kernel CSMain

#include "..\Common\CommonLibrary.hlsl"

Texture2D<float> _InTexture;
Texture2D<float> _RampTexture;
SamplerState sampler_RampTexture;

RWTexture2D<float> _OutTexture;

[numthreads(8, 8, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    uint2 uv = id.xy;
    
    float t = saturate(_InTexture[uv].r);
        
    float height = SampleCurve(_RampTexture, sampler_RampTexture, t);

    _OutTexture[uv].r = height;
}
